Basic project setup, entities and MySql in container
HNDaG/listening-platform pull request #2
Opened 2023-09-07 08:01 UTC by HNDaG

2023-09-07 14:13 UTC, HNDaG commented
@ajax-gnatiuk-s

2023-09-07 22:27 UTC, ajax-gnatiuk-s requested changes
Good work, but let's always use ` `(4 spaces) instead of `    `(1 tab)

2023-09-07 22:27 UTC, ajax-gnatiuk-s commented on src/test/kotlin/com/nikitahohulia/listeningplatform/ListeningPlatformApplicationTests.kt
> +	fun contextLoads() = Unit
tabs instead of spaces. please replace with ` `.

2023-09-07 22:27 UTC, ajax-gnatiuk-s commented on src/main/kotlin/com/nikitahohulia/listeningplatform/ListeningPlatformApplication.kt
> +	runApplication<ListeningPlatformApplication>(*args)
in here we have tabs

2023-09-07 22:27 UTC, ajax-gnatiuk-s commented on build.gradle.kts
> +	id("org.springframework.boot") version "3.1.3"
and here tabs

2023-09-08 07:37 UTC, ajax-gnatiuk-s approved these changes

2023-09-08 08:02 UTC, merged